src/Entity/Season.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SeasonRepository")
 */
class Season
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $air_date;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $poster_path;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $overview;

    /**
     * @ORM\Column(type="integer")
     */
    private $tmdb_show_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $season_number;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Show", inversedBy="seasons")
     * @ORM\JoinColumn(nullable=false)
     */
    private $show_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $episode_count;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Episode", mappedBy="season", orphanRemoval=true)
     */
    private $episodes;

    public function __construct()
    {
        $this->episodes = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAirDate(): ?\DateTimeInterface
    {
        return $this->air_date;
    }

    public function setAirDate(\DateTimeInterface $air_date): self
    {
        if($this->getAirDate() == null || $this->getAirDate()->getTimestamp() != $air_date->getTimestamp()) {
            $this->air_date = $air_date;
        }
        return $this;
    }

    public function getPosterPath(): ?string
    {
        return $this->poster_path;
    }

    public function setPosterPath(?string $poster_path): self
    {
        $this->poster_path = $poster_path;

        return $this;
    }

    public function getOverview(): ?string
    {
        return $this->overview;
    }

    public function setOverview(?string $overview): self
    {
        $this->overview = $overview;

        return $this;
    }

    public function getTmdbShowId(): ?int
    {
        return $this->tmdb_show_id;
    }

    public function setTmdbShowId(int $tmdb_show_id): self
    {
        $this->tmdb_show_id = $tmdb_show_id;

        return $this;
    }

    public function getSeasonNumber(): ?int
    {
        return $this->season_number;
    }

    public function setSeasonNumber(int $season_number): self
    {
        $this->season_number = $season_number;

        return $this;
    }

    public function getShow(): ?Show
    {
        return $this->show_id;
    }

    public function setShow(?Show $show_id): self
    {
        $this->show_id = $show_id;

        return $this;
    }

    public function getEpisodeCount(): ?int
    {
        return $this->episode_count;
    }

    public function setEpisodeCount(int $episode_count): self
    {
        $this->episode_count = $episode_count;

        return $this;
    }

    /**
     * @return Collection|Episode[]
     */
    public function getEpisodes(): Collection
    {
        return $this->episodes;
    }

    public function addEpisode(Episode $episode): self
    {
        if (!$this->episodes->contains($episode)) {
            $this->episodes[] = $episode;
            $episode->setSeason($this);
        }

        return $this;
    }

    public function removeEpisode(Episode $episode): self
    {
        if ($this->episodes->contains($episode)) {
            $this->episodes->removeElement($episode);
            // set the owning side to null (unless already changed)
            if ($episode->getSeason() === $this) {
                $episode->setSeason(null);
            }
        }

        return $this;
    }

    function hasPreviousSeason(){
        return $this->getSeasonNumber() > 1;
    }

    function hasNextSeason(){
        return $this->getShow()->getSeasonsCount() > $this->season_number;
    }
}

src/Entity/Show.php
<?php

namespace App\Entity;

use Carbon\Carbon;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ShowRepository")
 * @ORM\Table(name="tv_shows")
 */
class Show
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $backdrop_path;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $poster_path;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $first_air_date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $overview;

    /**
     * @ORM\Column(type="integer")
     */
    private $tmdb_id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Season", mappedBy="show_id", orphanRemoval=true)
     */
    private $seasons;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Episode", mappedBy="tv_show", orphanRemoval=true)
     */
    private $episodes;

    /**
     * @ORM\Column(type="boolean")
     */
    private $in_production;

    /**
     * @ORM\Column(type="datetime")
     */
    private $last_air_date;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    public function __construct()
    {
        $this->seasons = new ArrayCollection();
        $this->episodes = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getBackdropPath(): ?string
    {
        return $this->backdrop_path;
    }

    public function setBackdropPath(?string $backdrop_path): self
    {
        $this->backdrop_path = $backdrop_path;

        return $this;
    }

    public function getPosterPath(): ?string
    {
        return $this->poster_path;
    }

    public function setPosterPath(?string $poster_path): self
    {
        $this->poster_path = $poster_path;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstAirDate(): ?\DateTimeInterface
    {
        return $this->first_air_date;
    }

    public function setFirstAirDate(\DateTimeInterface $first_air_date): self
    {
        if($this->getFirstAirDate() == null || $this->getFirstAirDate()->getTimestamp() != $first_air_date->getTimestamp()) {
            $this->first_air_date = $first_air_date;
        }
        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getOverview(): ?string
    {
        return $this->overview;
    }

    public function setOverview(?string $overview): self
    {
        $this->overview = $overview;

        return $this;
    }

    public function getTmdbId(): ?int
    {
        return $this->tmdb_id;
    }

    public function setTmdbId(int $tmdb_id): self
    {
        $this->tmdb_id = $tmdb_id;

        return $this;
    }

    /**
     * @return Collection|Season[]
     */
    public function getSeasons(): Collection
    {
        return $this->seasons;
    }

    public function addSeason(Season $season): self
    {
        if (!$this->seasons->contains($season)) {
            $this->seasons[] = $season;
            $season->setShow($this);
        }

        return $this;
    }

    public function removeSeason(Season $season): self
    {
        if ($this->seasons->contains($season)) {
            $this->seasons->removeElement($season);
            // set the owning side to null (unless already changed)
            if ($season->getShow() === $this) {
                $season->setShow(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Episode[]
     */
    public function getEpisodes(): Collection
    {
        return $this->episodes;
    }

    public function addEpisode(Episode $episode): self
    {
        if (!$this->episodes->contains($episode)) {
            $this->episodes[] = $episode;
            $episode->setTvShow($this);
        }

        return $this;
    }

    public function removeEpisode(Episode $episode): self
    {
        if ($this->episodes->contains($episode)) {
            $this->episodes->removeElement($episode);
            // set the owning side to null (unless already changed)
            if ($episode->getTvShow() === $this) {
                $episode->setTvShow(null);
            }
        }

        return $this;
    }

    public function getSeasonsCount(){
        return $this->getSeasons()->count();
    }

    public function getSeasonByNumber($seasonNumber){
        foreach ($this->getSeasons() as $season){
            if ($season->getSeasonNumber() == $seasonNumber) return $season;
        }
        return null;
    }

    public function getUnairedEpisodes(){
        $yesterday = new \DateTime();
        $yesterday->add(\DateInterval::createFromDateString('yesterday'));
        return $this->episodes->filter(function (Episode $e) use ($yesterday){
            return $e->getAirDate() > $yesterday;
        });
    }

    public function getNextAiredEpisode(){
        $unairedEpisodes = $this->getUnairedEpisodes();
        if ($unairedEpisodes->isEmpty()){
            return null;
        }

        $nextEpisode = $unairedEpisodes->first();
        foreach ($unairedEpisodes as $e){
            if($nextEpisode->getAirDate() > $e->getAirDate()){
                $nextEpisode = $e;
            }
        }

        return $nextEpisode;
    }

    public function isHot(){
        $nextEpisode = $this->getNextAiredEpisode();
        if ($nextEpisode === null) return false;
        $airDate = Carbon::instance($nextEpisode->getAirDate());

        return $airDate->diffInDays(Carbon::now()) < 15;
    }

    public function getInProduction(): ?bool
    {
        return $this->in_production;
    }

    public function setInProduction(bool $in_production): self
    {
        $this->in_production = $in_production;

        return $this;
    }

    public function getLastAirDate(): ?\DateTimeInterface
    {
        return $this->last_air_date;
    }

    public function setLastAirDate(\DateTimeInterface $last_air_date): self
    {
        $this->last_air_date = $last_air_date;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * @return Show
     */
    public function setUpdatedAt(): self
    {
        $this->updated_at = new \DateTime();

        return $this;
    }


}

src/Controller/ShowController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Repository\MediaRepository;
use App\Repository\ShowRepository;
use App\Repository\TmdbRepository;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;

class ShowController extends Controller
{
    /**
     * @Route("/show/{showId}", name="show_show")
     */
    public function show($showId, TmdbRepository $tmdbRepository, MediaRepository $mediaRepository, AuthorizationCheckerInterface $authChecker)
    {
        $user = new User();
        $show = $mediaRepository->getShowByTmdbId($showId);

        $isInWatchlist = false;
        $isInFollowList = false;
        $isInHistory = false;
        if($authChecker->isGranted('ROLE_USER')){
            foreach ($this->getUser()->getWatchlist() as $s){
                if ($s->getTmdbId() == $showId){
                    $isInWatchlist = true;
                    break;
                }
            }
            foreach ($this->getUser()->getFollowlist() as $s){
                if ($s->getTmdbId() == $showId){
                    $isInFollowList = true;
                    break;
                }
            }
            $historyList = $this->getUser()->getHistory();
            $historyList = $historyList->filter(function ($e) use ($showId) {
               return $e->getTvShow()->getTmdbId() == $showId;
            });
            $isInHistory = $historyList->count() == $show->getEpisodes()->count();
        }

        return $this->render('show/show.html.twig', [
            'show'=>$show,
            'isInWatchlist' => $isInWatchlist,
            'isInFollowlist' => $isInFollowList,
            'isInHistory' => $isInHistory
        ]);
    }
}

templates/show/show.html.twig
{% extends 'media.html.twig' %}
{% block background_url%}{{ show.backdropPath }}{% endblock %}
{% block media_poster %}
    {% if show.isHot() %}
        <div class="top-left-corner-label">
            <i class="material-icons">whatshot</i>
        </div>
    {% endif%}
    <img src="{{ 'https://image.tmdb.org/t/p/w92' ~ show.posterPath }}" alt="">
{% endblock %}

{% block media_text %}
    <h1>{{ show.name }}
        <span class="date">{{ show.firstAirDate|date('Y') }}</span>
    </h1>
{% endblock %}

{% block media_actions %}
    <div class="action {{ isInFollowlist ? 'active' : '' }}" onclick="$('#form_followlist').submit()">
        <form id="form_followlist" action="{{ path('followlist_store',{tmdbId:show.tmdbId}) }}" method="post">
            {% if isInFollowlist %}
                <input value="DELETE" name="_method" hidden>
            {% endif %}
        </form>
        <i class="material-icons">bookmark_border</i> Suivre
    </div>
    <div class="action {{ isInHistory ? 'active' : '' }}" onclick="$('#show_history_form').submit()">
        <form id="show_history_form" action="{{ path("history_store_show", {tmdbId:show.tmdbId}) }}" method="post">
            {% if isInHistory %}
                <input value="DELETE" name="_method" hidden>
            {% endif %}
        </form>
        <i class="material-icons">{{ isInHistory ? 'clear' : 'done_all' }}</i>Marquer comme {{ isInHistory ? 'non ' }}vu
    </div>
    <div class="action {{ isInWatchlist ? 'active' : '' }}" onclick="$('#form_watchlist').submit()">
        <form id="form_watchlist" action="{{ isInWatchlist ? path('watchlist_delete',{tmdbId:show.tmdbId}) : path('watchlist_store',{tmdbId:show.tmdbId}) }}" method="post">
            {% if isInWatchlist %}
                <input value="DELETE" name="_method" hidden>
            {% endif %}
        </form>
        <i class="material-icons">list</i>A voir
    </div>

{% endblock %}

{% block content %}
    {#{{ dump(show) }}#}
    <section>
        <ul class="tabs">
            <li class="tab col s3">
                <a class="active" href="#synopsis">Synopsis</a>
            </li>
            <li class="tab col s3">
                <a href="#seasons">Saisons</a>
            </li>
            <li class="tab col s3">
                <a href="#planning">Planning</a>
            </li>
        </ul>
        <div class="container">
            <div id="synopsis" class="col s12">
                <div class="meta">
                    <label>DERNIÈRE DIFFUSION </label>{{ show.lastAirDate | date('d F Y') }}
                    <br>
                    <label>STATUT</label> {{ show.inProduction ? 'En Production' : 'Terminée' }}
                </div>
                {{ show.overview ? show.overview : "Le synopsis n'est pas disponible."}}
            </div>
            <div id="seasons" class="col s12">
                {% for season in show.seasons %}

                    {% set unwatchedEpisodesCount =  app.user ? season.episodes.count() - app.user.getWatchedEpisodeCountForSeason(show.tmdbId,season.seasonNumber) : season.episodes.count()%}
                <div class="season card horizontal">
                    <div class="card-image">
                        <img src="{{ 'https://image.tmdb.org/t/p/w94_and_h141_bestv2' ~ season.posterPath}}"
                             alt="">
                    </div>
                    <div class="card-stacked">
                        <div class="card-content">
                            <h1>
                                <a href="{{ path('season_show',{showId: show.tmdbId, seasonNumber: season.seasonNumber}) }}">Saison {{ season.seasonNumber }}</a>
                            </h1>
                            <h2>
                                {{ season.airDate | date('Y') }} | {{ season.episodeCount }} épisodes
                            </h2>
                            <h2>
                                {{ unwatchedEpisodesCount }} épisodes à voir
                            </h2>
                        </div>
                        <div class="card-action button {{ unwatchedEpisodesCount == 0 ? 'danger' }}" onclick="$('#form_watch_season_{{ season.seasonNumber }}').submit()">
                            <form id="form_watch_season_{{ season.seasonNumber }}" action="{{ path('history_store_season', {tmdbId:show.tmdbId,seasonNumber:season.seasonNumber}) }}" method="post">
                                {% if  unwatchedEpisodesCount == 0 %}
                                    <input value="DELETE" name="_method" hidden>
                                {% endif %}
                                <input value="{{ path('show_show', {showId:show.tmdbId}) }}" name="redirect" hidden>
                            </form>
                            {% if unwatchedEpisodesCount == 0 %}
                                <i class="material-icons">clear</i>Marquer comme non vu
                            {% else %}
                                <i class="material-icons">done_all</i>Marquer comme vu
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% else %}
                    Aucune saison pour l'instant
                {% endfor %}

            </div>

            <div id="planning" class="planning">
                {#{{ dump(show.getUnairedEpisodes()) }}#}
                {% for episode in show.getUnairedEpisodes() %}
                <div class="episode">
                    <h1>
                        <a href="{{ path('episode_show',{showId:show.tmdbId,seasonNumber:episode.seasonNumber,episodeNumber:episode.EpisodeNumber}) }}">{{ episode.seasonNumber }}x{{ episode.episodeNumber }} {{ episode.name }}</a>
                    </h1>
                    <h2>{{ episode.airDate | date_diff}}</h2>
                </div>
                {% else %}
                    Aucun épisode n'est annoncé.
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}