src/Entity/Episode.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EpisodeRepository")
 */
class Episode
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $air_date;

    /**
     * @ORM\Column(type="integer")
     */
    private $episode_number;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $overview;

    /**
     * @ORM\Column(type="integer")
     */
    private $season_number;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $still_path;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Show", inversedBy="episodes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $tv_show;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Season", inversedBy="episodes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $season;

    public function getId()
    {
        return $this->id;
    }

    public function getAirDate(): ?\DateTimeInterface
    {
        return $this->air_date;
    }

    public function setAirDate(\DateTimeInterface $air_date): self
    {
        if($this->getAirDate() == null || $this->getAirDate()->getTimestamp() != $air_date->getTimestamp()) {
            $this->air_date = $air_date;
        }
        return $this;
    }

    public function getEpisodeNumber(): ?int
    {
        return $this->episode_number;
    }

    public function setEpisodeNumber(int $episode_number): self
    {
        $this->episode_number = $episode_number;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getOverview(): ?string
    {
        return $this->overview;
    }

    public function setOverview(?string $overview): self
    {
        $this->overview = $overview;

        return $this;
    }

    public function getSeasonNumber(): ?int
    {
        return $this->season_number;
    }

    public function setSeasonNumber(int $season_number): self
    {
        $this->season_number = $season_number;

        return $this;
    }

    public function getStillPath(): ?string
    {
        return $this->still_path;
    }

    public function setStillPath(?string $still_path): self
    {
        $this->still_path = $still_path;

        return $this;
    }

    public function getTvShow(): ?Show
    {
        return $this->tv_show;
    }

    public function setTvShow(?Show $tv_show): self
    {
        $this->tv_show = $tv_show;

        return $this;
    }

    public function getSeason(): ?Season
    {
        return $this->season;
    }

    public function setSeason(?Season $season): self
    {
        $this->season = $season;

        return $this;
    }

    public function hasPreviousEpisode(){
        if ($this->getEpisodeNumber() > 1){
            return true;
        }
        return $this->getSeasonNumber() > 1 &&
            $this->getTvShow()->getSeasonByNumber($this->getSeasonNumber() - 1)->getEpisodeCount() > 0;
    }

    public function getPreviousEpisodeInfo(){
        if (!$this->hasPreviousEpisode()){
            return null;
        }
        if($this->getEpisodeNumber() > 1){
            return [
                'seasonNumber' => $this->getSeasonNumber(),
                'episodeNumber' => $this->getEpisodeNumber() - 1,
            ];
        }
        return [
            'seasonNumber' => $this->getSeasonNumber() - 1,
            'episodeNumber' => $this->getTvShow()->getSeasonByNumber($this->getSeasonNumber() - 1)->getEpisodeCount()
        ];
    }

    public function hasNextEpisode(){
        if($this->getEpisodeNumber() < $this->getSeason()->getEpisodeCount()){
            return true;
        }
        return $this->getSeason()->hasNextSeason() &&
            $this->getTvShow()->getSeasonByNumber($this->getSeasonNumber() + 1)->getEpisodeCount() > 0;
    }

    public function getNextEpisodeInfo(){
        if(!$this->hasNextEpisode()){
            return null;
        }
        if($this->getEpisodeNumber() < $this->getSeason()->getEpisodeCount()){
            return [
                'seasonNumber' => $this->getSeasonNumber(),
                'episodeNumber' => $this->getEpisodeNumber() + 1
            ];
        }
        return [
            'seasonNumber' => $this->getSeasonNumber() +1,
            'episodeNumber' => 1
        ];
    }
}

src/Entity/Season.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SeasonRepository")
 */
class Season
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $air_date;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $poster_path;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $overview;

    /**
     * @ORM\Column(type="integer")
     */
    private $tmdb_show_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $season_number;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Show", inversedBy="seasons")
     * @ORM\JoinColumn(nullable=false)
     */
    private $show_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $episode_count;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Episode", mappedBy="season", orphanRemoval=true)
     */
    private $episodes;

    public function __construct()
    {
        $this->episodes = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAirDate(): ?\DateTimeInterface
    {
        return $this->air_date;
    }

    public function setAirDate(\DateTimeInterface $air_date): self
    {
        if($this->getAirDate() == null || $this->getAirDate()->getTimestamp() != $air_date->getTimestamp()) {
            $this->air_date = $air_date;
        }
        return $this;
    }

    public function getPosterPath(): ?string
    {
        return $this->poster_path;
    }

    public function setPosterPath(?string $poster_path): self
    {
        $this->poster_path = $poster_path;

        return $this;
    }

    public function getOverview(): ?string
    {
        return $this->overview;
    }

    public function setOverview(?string $overview): self
    {
        $this->overview = $overview;

        return $this;
    }

    public function getTmdbShowId(): ?int
    {
        return $this->tmdb_show_id;
    }

    public function setTmdbShowId(int $tmdb_show_id): self
    {
        $this->tmdb_show_id = $tmdb_show_id;

        return $this;
    }

    public function getSeasonNumber(): ?int
    {
        return $this->season_number;
    }

    public function setSeasonNumber(int $season_number): self
    {
        $this->season_number = $season_number;

        return $this;
    }

    public function getShow(): ?Show
    {
        return $this->show_id;
    }

    public function setShow(?Show $show_id): self
    {
        $this->show_id = $show_id;

        return $this;
    }

    public function getEpisodeCount(): ?int
    {
        return $this->episode_count;
    }

    public function setEpisodeCount(int $episode_count): self
    {
        $this->episode_count = $episode_count;

        return $this;
    }

    /**
     * @return Collection|Episode[]
     */
    public function getEpisodes(): Collection
    {
        return $this->episodes;
    }

    public function addEpisode(Episode $episode): self
    {
        if (!$this->episodes->contains($episode)) {
            $this->episodes[] = $episode;
            $episode->setSeason($this);
        }

        return $this;
    }

    public function removeEpisode(Episode $episode): self
    {
        if ($this->episodes->contains($episode)) {
            $this->episodes->removeElement($episode);
            // set the owning side to null (unless already changed)
            if ($episode->getSeason() === $this) {
                $episode->setSeason(null);
            }
        }

        return $this;
    }

    function hasPreviousSeason(){
        return $this->getSeasonNumber() > 1;
    }

    function hasNextSeason(){
        return $this->getShow()->getSeasonsCount() > $this->season_number;
    }
}

src/Entity/Show.php
<?php

namespace App\Entity;

use Carbon\Carbon;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ShowRepository")
 * @ORM\Table(name="tv_shows")
 */
class Show
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $backdrop_path;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $poster_path;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $first_air_date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $overview;

    /**
     * @ORM\Column(type="integer")
     */
    private $tmdb_id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Season", mappedBy="show_id", orphanRemoval=true)
     */
    private $seasons;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Episode", mappedBy="tv_show", orphanRemoval=true)
     */
    private $episodes;

    /**
     * @ORM\Column(type="boolean")
     */
    private $in_production;

    /**
     * @ORM\Column(type="datetime")
     */
    private $last_air_date;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    public function __construct()
    {
        $this->seasons = new ArrayCollection();
        $this->episodes = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getBackdropPath(): ?string
    {
        return $this->backdrop_path;
    }

    public function setBackdropPath(?string $backdrop_path): self
    {
        $this->backdrop_path = $backdrop_path;

        return $this;
    }

    public function getPosterPath(): ?string
    {
        return $this->poster_path;
    }

    public function setPosterPath(?string $poster_path): self
    {
        $this->poster_path = $poster_path;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstAirDate(): ?\DateTimeInterface
    {
        return $this->first_air_date;
    }

    public function setFirstAirDate(\DateTimeInterface $first_air_date): self
    {
        if($this->getFirstAirDate() == null || $this->getFirstAirDate()->getTimestamp() != $first_air_date->getTimestamp()) {
            $this->first_air_date = $first_air_date;
        }
        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getOverview(): ?string
    {
        return $this->overview;
    }

    public function setOverview(?string $overview): self
    {
        $this->overview = $overview;

        return $this;
    }

    public function getTmdbId(): ?int
    {
        return $this->tmdb_id;
    }

    public function setTmdbId(int $tmdb_id): self
    {
        $this->tmdb_id = $tmdb_id;

        return $this;
    }

    /**
     * @return Collection|Season[]
     */
    public function getSeasons(): Collection
    {
        return $this->seasons;
    }

    public function addSeason(Season $season): self
    {
        if (!$this->seasons->contains($season)) {
            $this->seasons[] = $season;
            $season->setShow($this);
        }

        return $this;
    }

    public function removeSeason(Season $season): self
    {
        if ($this->seasons->contains($season)) {
            $this->seasons->removeElement($season);
            // set the owning side to null (unless already changed)
            if ($season->getShow() === $this) {
                $season->setShow(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Episode[]
     */
    public function getEpisodes(): Collection
    {
        return $this->episodes;
    }

    public function addEpisode(Episode $episode): self
    {
        if (!$this->episodes->contains($episode)) {
            $this->episodes[] = $episode;
            $episode->setTvShow($this);
        }

        return $this;
    }

    public function removeEpisode(Episode $episode): self
    {
        if ($this->episodes->contains($episode)) {
            $this->episodes->removeElement($episode);
            // set the owning side to null (unless already changed)
            if ($episode->getTvShow() === $this) {
                $episode->setTvShow(null);
            }
        }

        return $this;
    }

    public function getSeasonsCount(){
        return $this->getSeasons()->count();
    }

    public function getSeasonByNumber($seasonNumber){
        foreach ($this->getSeasons() as $season){
            if ($season->getSeasonNumber() == $seasonNumber) return $season;
        }
        return null;
    }

    public function getUnairedEpisodes(){
        $yesterday = new \DateTime();
        $yesterday->add(\DateInterval::createFromDateString('yesterday'));
        return $this->episodes->filter(function (Episode $e) use ($yesterday){
            return $e->getAirDate() > $yesterday;
        });
    }

    public function getNextAiredEpisode(){
        $unairedEpisodes = $this->getUnairedEpisodes();
        if ($unairedEpisodes->isEmpty()){
            return null;
        }

        $nextEpisode = $unairedEpisodes->first();
        foreach ($unairedEpisodes as $e){
            if($nextEpisode->getAirDate() > $e->getAirDate()){
                $nextEpisode = $e;
            }
        }

        return $nextEpisode;
    }

    public function isHot(){
        $nextEpisode = $this->getNextAiredEpisode();
        if ($nextEpisode === null) return false;
        $airDate = Carbon::instance($nextEpisode->getAirDate());

        return $airDate->diffInDays(Carbon::now()) < 15;
    }

    public function getInProduction(): ?bool
    {
        return $this->in_production;
    }

    public function setInProduction(bool $in_production): self
    {
        $this->in_production = $in_production;

        return $this;
    }

    public function getLastAirDate(): ?\DateTimeInterface
    {
        return $this->last_air_date;
    }

    public function setLastAirDate(\DateTimeInterface $last_air_date): self
    {
        $this->last_air_date = $last_air_date;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * @return Show
     */
    public function setUpdatedAt(): self
    {
        $this->updated_at = new \DateTime();

        return $this;
    }


}

src/Controller/SeasonController.php
<?php

namespace App\Controller;

use App\Repository\MediaRepository;
use App\Repository\TmdbRepository;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;

class SeasonController extends Controller
{
    /**
     * @Route("show/{showId}/season/{seasonNumber}", name="season_show")
     * @param $showId
     * @param $seasonNumber
     * @param MediaRepository $mediaRepository
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function index($showId,$seasonNumber, MediaRepository $mediaRepository, AuthorizationCheckerInterface $authChecker)
    {
        $season = $mediaRepository->getSeasonByTmdbId($showId,$seasonNumber);
        $isInHistory = false;
        if($authChecker->isGranted('ROLE_USER')) {
            $isInHistory = $this->getUser()->getWatchedEpisodeCountForSeason($showId, $seasonNumber) == $season->getEpisodes()->count();
        }
        return $this->render('season/show.html.twig', [
            'season' => $season,
            'isInHistory' => $isInHistory
        ]);
    }
}

templates/season/show.html.twig
{% extends 'media.html.twig' %}
{% block background_url %}{{ season.show.backdropPath }}{% endblock %}
    {% block media_poster %}
        {% if season.show.isHot() %}
            <div class="top-left-corner-label">
                <i class="material-icons">whatshot</i>
            </div>
        {% endif%}
        <img src="https://image.tmdb.org/t/p/w92/{{ season.posterPath}}" alt="">
    {% endblock %}

    {% block media_text %}
        <h2>
            <a href="{{ path('show_show',{showId:season.show.tmdbId}) }}">{{ season.show.name }}</a>
        </h2>
        <h1>Saison {{ season.seasonNumber }}
            <span class="date">{{ season.airDate | date('Y') }}</span>
        </h1>
    {% endblock %}

    {% block media_actions %}
        <div class="action {{ season.hasPreviousSeason() ? '' : 'hidden' }}">
            <a href="{{ season.hasPreviousSeason() ? path('season_show',{showId:season.show.tmdbId,seasonNumber:season.seasonNumber - 1}) : '#' }}">
                <i class="material-icons">chevron_left</i>
            </a>
        </div>
        <div class="action {{ isInHistory ? 'active' }}" onclick="$('#form_season_history').submit()">
            <form id="form_season_history" action="{{ path('history_store_season',{tmdbId:season.show.tmdbId,seasonNumber:season.seasonNumber}) }}" method="post">
                {% if isInHistory %}
                    <input name="_method" value="delete" hidden>
                {% endif %}
            </form>
            {% if isInHistory %}
                <i class="material-icons">clear</i>Marquer comme non vu
            {% else %}
                <i class="material-icons">done_all</i>Marquer comme vu
            {% endif %}
        </div>
        <div class="action {{ season.hasNextSeason() ? '' : 'hidden' }}">
            <a href="{{ season.hasNextSeason() ? path('season_show',{showId:season.show.tmdbId,seasonNumber:season.seasonNumber + 1}) : '#' }}">
                <i class="material-icons">chevron_right</i>
            </a>
        </div>
    {% endblock %}

    {% block content %}
        {#{{ dump(season) }}#}
        <section>
            <ul class="tabs">
                <li class="tab col s3">
                    <a class="active" href="#synopsis">Synopsis</a>
                </li>
                <li class="tab col s3">
                    <a href="#episodes">Episodes</a>
                </li>
            </ul>
            <div class="container">
                <div id="synopsis" class="col s12">
                    {{ season.overview ? season.overview : "Le synopsis n'est pas disponible"}}
                </div>
                <div id="episodes" class="col s12 episodes">
                    {% for episode in season.episodes %}
                        {% set isEpWatched = app.user ? app.user.isEpisodeWatched(episode): false %}
                        <div class="episode">
                            <div>
                                <h1>
                                    <a href="{{ path('episode_show',{showId:season.show.tmdbId,seasonNumber:season.seasonNumber,episodeNumber:episode.episodeNumber}) }}">{{ season.seasonNumber }}x{{ episode.episodeNumber }} -
                                        {{ episode.name }}</a>
                                </h1>
                                <h2>{{ episode.airDate | date('d F Y') }}</h2>
                            </div>
                            <form action="{{ path('history_store_episode',{tmdbId: episode.tvShow.id, seasonNumber: season.seasonNumber, episodeNumber:episode.episodeNumber}) }}" method="post">
                                {% if isEpWatched %}
                                    <input name="_method" value="delete" hidden>
                                {% endif %}
                                <input name="redirect" value="{{ path('season_show',{showId: season.show.tmdbId, seasonNumber: season.seasonNumber}) }}" hidden>
                                <button type="submit" class="btn waves-effect waves-light {{ isEpWatched ? 'red' : 'green' }}">
                                    <i class="material-icons">{{ isEpWatched ? 'clear' : 'check' }}</i>
                                </button>
                            </form>

                        </div>
                    {% else %}
                        Aucun épisode pour l'instant.
                    {% endfor %}
                </div>
            </div>
        </section>
    {% endblock %}